# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Detrans
version:      1.2
version_from: lib/MARC/Detrans.pm
installdirs:  site
requires:
    Class::Accessor:               0.19
    MARC::Record:                  1.38
    Test::Exception:               0
    XML::SAX:                      0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
