#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Detrans
version:      0.97
version_from: lib/MARC/Detrans.pm
installdirs:  site
requires:
    Test::Exception:               0
    MARC::Record:                  1.38
    XML::SAX:                      0.12
    Class::Accessor:               0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
