#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Detrans
version:      0.9
version_from: lib/MARC/Detrans.pm
installdirs:  site
requires:
    MARC::Record:                  1.38
    Class::Accessor:               0.19
    Test::Exception:               0
    XML::SAX:                      0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
