#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-Detrans
version:      0.1
version_from: lib/MARC/Detrans.pm
installdirs:  site
requires:
    XML::SAX:                      0
    Class::Accessor:               0
    MARC::Record:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
